---
 src/Makefile.am |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- nano-1.3.4.orig/src/Makefile.am
+++ nano-1.3.4/src/Makefile.am
@@ -1,6 +1,6 @@
 DEFS= -DSYSCONFDIR=\"$(sysconfdir)\"
 localedir = $(datadir)/locale
-INCLUDES = -Iintl -DLOCALEDIR=\"$(localedir)\" -I@includedir@
+INCLUDES = -Iintl -DLOCALEDIR=\"$(localedir)\"
 
 ACLOCAL_AMFLAGS = -I m4
 
