---
 Makefile.am |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- nano-1.0.7.orig/Makefile.am
+++ nano-1.0.7/Makefile.am
@@ -30,7 +30,7 @@ EXTRA_DIST =	ABOUT-NLS AUTHORS BUGS COPY
 SUBDIRS = po intl
 
 localedir = $(datadir)/locale
-INCLUDES = -Iintl -DLOCALEDIR=\"$(localedir)\" -I@includedir@
+INCLUDES = -Iintl -DLOCALEDIR=\"$(localedir)\"
 
 $(srcdir)/acinclude.m4: $(ACINCLUDE_INPUTS)
 	cat $(ACINCLUDE_INPUTS) > $@
